### ISSUE TITLE
Installing on pc196 at UCL HEP

### ISSUE THREAD

**Issue by edbird** [SuperNEMO-DBD/brew#14] opened 2019-09-13 12:55 UTC
Info:

brew snemo-doctor
Please note that these warnings are just used to help the SuperNEMO maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/attr_node_func.h
  /usr/local/include/chk_file_sec.h
  /usr/local/include/common_cmds.h
  /usr/local/include/lib_ifl.h
  /usr/local/include/lib_net.h
  /usr/local/include/lib_utils.h
  /usr/local/include/log_event.h
  /usr/local/include/pbs_log.h
  /usr/local/include/pbsnodes.h
  /usr/local/include/qsub_functions.h
  /usr/local/include/setup_env.h
  /usr/local/include/trq_auth_daemon.h
  /usr/local/include/u_lock_ctl.h

Warning: An outdated version (1.8.3.1) of Git was detected in your PATH.
Git 2.7.0 or newer is required for Homebrew.
Please upgrade:
  brew install git

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You may encounter build failures with some formulae as
brew is being run in an unsupported configuration
In these cases, please raise an issue at https://github.com/SuperNEMO-DBD/homebrew-core/issues

[ebirdsall@pc196 ~]$ brew install git
==> Installing dependencies for git: gettext, bzip2, pcre2, openssl, curl, libbsd and expat
==> Installing git dependency: gettext
==> Downloading https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
Already downloaded: /home/ebirdsall/.cache/Homebrew/downloads/9d18bbc4036e7ebcce01a57f3b21c17bd5e67618e25231698c8e8ec9ead922f9--gettext-0.19.8.1.tar.xz
==> Downloading http://xmlsoft.org/sources/libxml2-2.9.7.tar.gz
Already downloaded: /home/ebirdsall/.cache/Homebrew/downloads/32f8e17935c44a004fe0c1db6777e3e0829abd419eebe79e1b06b6c158690015--libxml2-2.9.7.tar.gz
==> ./configure --prefix=/home/ebirdsall/snemo-sdk/Cellar/gettext/0.19.8.1_1/libexec --without-python --without-lzma
==> make install
==> ./configure --disable-silent-rules --prefix=/home/ebirdsall/snemo-sdk/Cellar/gettext/0.19.8.1_1  --with-included-glib --with-included-libcroco --with-included-libunistring --with-emacs --with-lispdir=/home/ebirdsall/snemo-sdk/Cellar/ge
==> make
Last 15 lines from /home/ebirdsall/.cache/Homebrew/Logs/gettext/04.make:
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -DEXEEXT=\"\" -DEXEEXT=\"\" -DEXEEXT=\"\" -I. -I.. -I../intl -I../intl -I.. -I.. -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1 -I///usr/include/libxml2 -I./libcroco -g -O2 -c dup-safer.c  -fPIC -DPIC -o .libs/dup-safer.o
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -DEXEEXT=\"\" -DEXEEXT=\"\" -DEXEEXT=\"\" -I. -I.. -I../intl -I../intl -I.. -I.. -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1 -I///usr/include/libxml2 -I./libcroco -g -O2 -c unistd.c  -fPIC -DPIC -o .libs/unistd.o
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -DEXEEXT=\"\" -DEXEEXT=\"\" -DEXEEXT=\"\" -I. -I.. -I../intl -I../intl -I.. -I.. -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1 -I///usr/include/libxml2 -I./libcroco -g -O2 -c trim.c -o trim.o >/dev/null 2>&1
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -DEXEEXT=\"\" -DEXEEXT=\"\" -DEXEEXT=\"\" -I. -I.. -I../intl -I../intl -I.. -I.. -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1 -I///usr/include/libxml2 -I./libcroco -g -O2 -c unistd.c -o unistd.o >/dev/null 2>&1
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -DEXEEXT=\"\" -DEXEEXT=\"\" -DEXEEXT=\"\" -I. -I.. -I../intl -I../intl -I.. -I.. -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1 -I///usr/include/libxml2 -I./libcroco -g -O2 -c dup-safer.c -o dup-safer.o >/dev/null 2>&1
make[5]: Leaving directory `/tmp/gettext-20190913-10620-19237o/gettext-0.19.8.1/gettext-tools/gnulib-lib'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/tmp/gettext-20190913-10620-19237o/gettext-0.19.8.1/gettext-tools/gnulib-lib'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/tmp/gettext-20190913-10620-19237o/gettext-0.19.8.1/gettext-tools'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/gettext-20190913-10620-19237o/gettext-0.19.8.1/gettext-tools'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/gettext-20190913-10620-19237o/gettext-0.19.8.1'
make: *** [all] Error 2

READ THIS: https://github.com/SuperNEMO-DBD/brew/issues
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."

**Info from /home/ebirdsall/.cache/Homebrew/Logs/gettext/04.make**

In file included from term-styled-ostream.oo.c:26:0:
./libcroco/cr-sel-eng.h:34:26: fatal error: libxml/tree.h: No such file or directory
  #include <libxml/tree.h>
                          ^
compilation terminated.

Any ideas why this occurs? Any other info needed? Thanks, Ed

**Comment by drbenmorgan** [comment] 2019-09-13 13:21
Which OS/Version is this? The build is, fo some reason, picking up the system install of `libxml2` and failing because of that. Can you also run and post the output of `brew config` and `brew cat gettext` please?

**Comment by edbird** [comment] 2019-09-21 11:18
Hi, apparently it is CentOS7

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

This is brew config:

```
brew config
HOMEBREW_VERSION: >=1.7.1 (shallow or no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 1cb3492fed7ee65122af80236943e3e2d2db8417
Last commit: 10 weeks ago
Core tap ORIGIN: https://github.com/supernemo-dbd/homebrew-core
Core tap HEAD: 42eced045a27fe8de43d502bd9cfe7f87e9e77dc
Core tap last commit: 10 weeks ago
HOMEBREW_PREFIX: /home/ebirdsall/snemo-sdk
HOMEBREW_REPOSITORY: /home/ebirdsall/snemo-sdk
HOMEBREW_CELLAR: /home/ebirdsall/snemo-sdk/Cellar
HOMEBREW_CACHE: /home/ebirdsall/.cache/Homebrew
HOMEBREW_BUILD_FROM_SOURCE: 1
HOMEBREW_LOGS: /home/ebirdsall/.cache/Homebrew/Logs
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
HOMEBREW_XDG_RUNTIME_DIR: /run/user/8415
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /home/ebirdsall/snemo-sdk/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 1.8.3.1 => /bin/git
Curl: 7.29.0 => /usr/bin/curl
Kernel: Linux 3.10.0-957.10.1.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.7.1908 (Core) (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: N/A
gcc: N/A
xorg: N/A
```

and this is

```
brew cat gettext
class Gettext < Formula
  desc "GNU internationalization (i18n) and localization (l10n) library"
  homepage "https://www.gnu.org/software/gettext/"
  url "https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz"
  mirror "https://ftpmirror.gnu.org/gettext/gettext-0.19.8.1.tar.xz"
  sha256 "105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4"
  revision 1 unless OS.mac?

  bottle do
    sha256 "afc6a6120632b98d58b11fab82ae5e081206b89684dd948abf2d29caeb813ffd" => :mojave
    sha256 "99d2dbd4c9ebfe9bf2a64bd99f3a695a18635f0d9110eaff34bab8022abef6a8" => :high_sierra
    sha256 "8368522242c5fe33acd5c80b5f1321559da9efe20878da6e4b9507683a740c21" => :sierra
    sha256 "311475f36f3fd314ae0db4fb52e4ab769f62ded6c8c81678ad8295f41762e4ba" => :el_capitan
    sha256 "ca8fe572e7c8db00bb1bdfd66c379ba4a960927f4b829f47f9e2335c51dc7376" => :yosemite
    sha256 "e3091192716347fc54f6e8a8184d892feed5309672daa061a1407b071af80c05" => :mavericks
    sha256 "2f7c8ce5517ede83ad930e05e758cc330700e72c715c647540ffb122057d1109" => :x86_64_linux
  end

  keg_only :shadowed_by_macos,
    "macOS provides the BSD gettext library & some software gets confused if both are in the library path"

  unless OS.mac?
    depends_on "ncurses"
    depends_on "zlib" # for libxml2
    # libxml2 is vendored here to break a cyclic dependency:
    # python -> tcl-tk -> xorg -> libxpm -> gettext -> libxml2 -> python
    resource("libxml2") do
      url "http://xmlsoft.org/sources/libxml2-2.9.7.tar.gz"
      mirror "ftp://xmlsoft.org/libxml2/libxml2-2.9.7.tar.gz"
      sha256 "f63c5e7d30362ed28b38bfa1ac6313f9a80230720b7fb6c80575eeab3ff5900c"
    end
  end

  def install
    resource("libxml2").stage do
      system "./configure", "--disable-dependency-tracking",
                            "--prefix=#{libexec}",
                            "--without-python",
                            "--without-lzma"
      system "make", "install"
    end unless OS.mac?

    system "./configure", "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--disable-debug",
                          "--prefix=#{prefix}",
                          ("--with-included-gettext" if OS.mac?),
                          "--with-included-glib",
                          "--with-included-libcroco",
                          "--with-included-libunistring",
                          "--with-emacs",
                          "--with-lispdir=#{elisp}",
                          "--disable-java",
                          "--disable-csharp",
                          # Don't use VCS systems to create these archives
                          "--without-git",
                          "--without-cvs",
                          "--without-xz",
                          ("--with-libxml2-prefix=#{libexec}" unless OS.mac?),
                          ("--with-libxml2-prefix=#{Formula["libxml2"].opt_prefix}" if OS.mac?)
    system "make"
    ENV.deparallelize # install doesn't support multiple make jobs
    system "make", "install"
  end

  test do
    system bin/"gettext", "test"
  end
end
```

**Comment by drbenmorgan** [comment] 2019-09-23 10:11
Thanks! I'm not able to reproduce the issue on a CentOS7 Docker image with system libxml2 installed. Could you please run

```
$ brew gist-logs gettext
```

and post the link(s) generated please?

**Comment by edbird** [comment] 2019-09-23 11:47
brew gist-logs gettext
You can create a new personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile

GitHub User: edbird
Password: 

Error: GitHub Requires authentication:The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile

Sorry I'm not familiar with this process. I clicked the bottom link and created a token, which I saved to my desktop. Do you need this info? Is it secure to post it here or should I give it to you via another method?

**Comment by drbenmorgan** [comment] 2019-09-23 12:26
The token should just be a long hash, you shouldn't post it here since it gives access to your GitHub Account. Simply follow the instructions as printed, do:

```
$ export HOMEBREW_GITHUB_API_TOKEN=<the long hash>
$ brew gist-logs gettext
```

**Comment by edbird** [comment] 2019-09-27 12:06
Is this the thing you required?

https://gist.github.com/edbird/c2eb1f17c4e5a56c5cd3399ea769c5ee

**Comment by drbenmorgan** [comment] 2019-09-27 20:16
Yes, thanks! Also, what packages do you have installed, i.e., what does

```
$ brew ls
```

print? All I can think is that the system compiler is being used and that's causing the pick up of the system libxml2.

Did you try the exact "from scratch" instructions here : https://github.com/SuperNEMO-DBD/brew#installing-natively-from-scratch

**Comment by edbird** [comment] 2019-10-01 16:38
Hi again. answer is:

```
brew ls
gcc@7  gmp  gpatch  isl  libmpc  m4  mpfr  ncurses  pkg-config	zlib
```

will try following again and update you

**Comment by drbenmorgan** [comment] 2020-04-21 20:50
Closing due to lack of updates

**Closed as completed by drbenmorgan** 2020-04-21 20:50 UTC
